// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB31Ow11mu3-J_a-qUnGvnRfDbYaXOeFsw',
    appId: '1:431821472096:web:9d871c27d770c2170d5e05',
    messagingSenderId: '431821472096',
    projectId: 'flutter-user-366b2',
    authDomain: 'flutter-user-366b2.firebaseapp.com',
    storageBucket: 'flutter-user-366b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7UfUpWdOk_NDF6heZItNCRecCpRAxCU',
    appId: '1:431821472096:android:9b5504444d4bf3890d5e05',
    messagingSenderId: '431821472096',
    projectId: 'flutter-user-366b2',
    storageBucket: 'flutter-user-366b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxOYTdDKWymhrHbz5awT0Nix8woGFlMSM',
    appId: '1:431821472096:ios:eeea8db724d9314b0d5e05',
    messagingSenderId: '431821472096',
    projectId: 'flutter-user-366b2',
    storageBucket: 'flutter-user-366b2.appspot.com',
    iosBundleId: 'com.example.flutterUsers',
  );
}
